server:
  port: 8888

spring:
  application:
    name: config-service
  output:
    ansi.enabled: always
  cloud:
    config:
      server:
        git:
          uri: file://c:\workspace\git-local-repo

